name: AnyKernelTest

on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [AnyKernelTest]

jobs:
  package:
    runs-on: ubuntu-latest
    env:
      VERSION: "LineageOS-20"
      ZIP_NO_KSU: "${{ env.VERSION }}-NoKernelSU.zip"
      ZIP_KSU: "${{ env.VERSION }}-KernelSU.zip"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y zip
          mkdir -p outw/{true,false} AnyKernel3 output
          cp anykernel_test/Image.gz-dtb outw/false/
          cp anykernel_test/Image.gz-dtb outw/true/

      - name: Package kernels
        run: |
          chmod +x makezip.sh
          ./makezip.sh

      - name: Verify packages
        run: |
          ls -lh output/
          [ -f "output/$ZIP_NO_KSU" ] || { echo "Missing $ZIP_NO_KSU"; exit 1; }
          [ -f "output/$ZIP_KSU" ] || { echo "Missing $ZIP_KSU"; exit 1; }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-packages
          path: output/*.zip

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: output/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Kernel Package - ${{ env.VERSION }}"
          tag_name: "package-${{ github.run_number }}"
          body: |
            Pre-built kernel packages.
            Contains both standard and KernelSU versions.
          draft: false
          prerelease: false
