name: KernelSUOnly

on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-KernelSU-build]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["LineageOS-20"]

    env:
      VERSION: ${{ matrix.version }}
      ARCH: arm64
      KBUILD_BUILD_HOST: Github-Action
      KBUILD_BUILD_USER: "KernelSU_Builder"
      CLANG_PATH: ${{ github.workspace }}/kernel/clang/bin

    steps:
      # ... (wcześniejsze kroki pozostają bez zmian)

      - name: Set KERNELSU_VERSION environment variable
        run: echo "KERNELSU_VERSION=$(cat ksu_version.txt)" >> $GITHUB_ENV

      - name: Compile kernel with KernelSU support
        run: |
          chmod +x buildSU.sh
          ./buildSU.sh
        env:
          VERSION: ${{ matrix.version }}
          KERNELSU_VERSION: ${{ env.KERNELSU_VERSION }}

      # ... (reszta kroków pozostaje bez zmian)

      - name: Move kernel with KernelSU support to output directory
        run: |
          chmod +x move.sh
          ./move.sh

      - name: Extract Kernel Image path
        run: |
          echo "KERNEL_IMAGE=/home/runner/work/Kernel_Test/Kernel_Test/kernel/out/arch/arm64/boot/Image.gz-dtb" >> $GITHUB_ENV

      - name: Make a release
        uses: softprops/action-gh-release@v1
        with:
          files: |
             ${{ env.KERNEL_IMAGE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Kernel Release - ${{ env.VERSION }}
          tag_name: ${{ github.run_id }}
          body: |
             **Info:**
              - KernelSU Version: ${{ env.VERSION }}.
            
              <details>
                <summary>Build Settings</summary>
                  ```
                  ${{ env.buildsettings }}
                  ```
              </details>
          draft: false
          prerelease: false
