name: KernelSU 1.0.3 Builder

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: "LineageOS-20"
      ARCH: arm64
      CLANG_PATH: ${{ github.workspace }}/clang/bin
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y python3 python3-pip jq git-lfs clang llvm lld
          pip3 install pyyaml

      - name: Clone sources
        run: |
          git clone https://github.com/HowWof/android_kernel_realme_mt6785.git -b lineage-20 kernel
          git clone --depth=1 https://gitlab.com/Jprimero15/lolz_clang.git clang

      - name: Apply KernelSU 1.0.3
        run: chmod +x kernelSU.sh && ./kernelSU.sh

      - name: Build kernel
        run: chmod +x build.sh && ./build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: kernel-Image.gz-dtb
          path: kernel/out/arch/arm64/boot/Image.gz-dtb
