name: Kernel Bez SU

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["LineageOS-20"]

    env:
      VERSION: ${{ matrix.version }}
      ARCH: arm64
      KBUILD_BUILD_HOST: Github-Action
      KBUILD_BUILD_USER: "Kernel_Builder"
      CLANG_PATH: ${{ github.workspace }}/clang/bin
      DRIVERS_CONFIG: "${{ github.workspace }}/drivers.cfg"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify files
        run: |
          echo "Repository contents:"
          ls -la
          echo "KernelSU files:"
          ls -la kernelSU.sh build.sh clone.sh || true

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip jq
          sudo pip3 install pyyaml

      - name: Set up ccache
        run: |
          echo "/usr/lib/ccache" >> $GITHUB_PATH
          echo "USE_CCACHE=1" >> $GITHUB_ENV

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Clone clang and kernel sources
        run: |
          chmod +x clone.sh
          ./clone.sh

      - name: Add Clang to PATH
        run: |
          echo "${CLANG_PATH}" >> $GITHUB_PATH

      - name: Set KERNELSU environment variable to true
        run: echo "KERNELSU=true" >> $GITHUB_ENV

      - name: Set KERNELSU_VERSION environment variable
        run: echo "KERNELSU_VERSION=$(cat ksu_version.txt)" >> $GITHUB_ENV

      - name: Add KernelSU support
        run: |
          if [ -f "kernelSU.sh" ]; then
            chmod +x kernelSU.sh
            ./kernelSU.sh
          else
            echo "kernelSU.sh not found, using alternative method"
            curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s $KERNELSU_VERSION
          fi

      - name: Build kernel with drivers
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          if [ -f "kernel/out/arch/arm64/boot/Image.gz-dtb" ]; then
            cp kernel/out/arch/arm64/boot/Image.gz-dtb artifacts/
          elif [ -f "out/arch/arm64/boot/Image.gz-dtb" ]; then
            cp out/arch/arm64/boot/Image.gz-dtb artifacts/
          else
            echo "Error: Kernel image not found!"
            find . -name "Image.gz-dtb"
            exit 1
          fi

      - name: Make a release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/Image.gz-dtb
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Kernel Release - ${{ env.VERSION }}
          tag_name: ${{ github.run_id }}
          body: |
             **Info:**
              - Kernel Version: ${{ env.VERSION }}
              - KernelSU Version: ${{ env.KERNELSU_VERSION }}
              - Included Drivers: $(if [ -f "$DRIVERS_CONFIG" ]; then cat "$DRIVERS_CONFIG"; else echo "None"; fi)
              
              **Installation:**
              - Place Image.gz-dtb to /boot
          draft: false
          prerelease: false
